### PR TITLE
fixed broken method

### PR DESCRIPTION
**Pull request by robo220**

### CODE REVIEW

**Comment by lkm** [comment]
The method uses PHP’s late static binding, which you can easily google if in doubt

**Comment by robo220** [comment]
Ok I shall revert this

**Comment by robo220** [comment]
@lkm I think we need to change this somewhat. Someone using this method will call this and see that it fails. It's not entirely clear that we're using late static binding here. If you want the method is callable I think we should have a default type.

**Comment by lkm** [comment]
@robo220 Hrmm does the request fail at present? If so I think you have two options: 1) change the method to abstract, which you prevent the use of this on Book but also make it impossible to get all types of books in the same request or 2) make a condition if _OWN_TYPE == “” then don’t include the bookType in the request. I’m partial to the second

**Comment by robo220** [comment]
@lkm oops I amended my comment above to make more sense. I shall make a PR and get it reviewed from @AthanasiosKoumpouras and yourself.

**Pull request merged**
